name: CI

on:
  pull_request:
    branches: [main]

jobs:
  lint_prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - run: corepack enable pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm prettier --check .

  lint_eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - run: corepack enable pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm lint
